### ISSUE TITLE
Parser: Fixa så att datat läses in i rätt (UTF?) format

### ISSUE THREAD

**Issue by winterrobert** [Senseworks-io/parser#1]
![image](https://user-images.githubusercontent.com/28933730/73125363-37b5be00-3fa6-11ea-9e66-88a8dc3e8dde.png)

**Comment by MrSinclair** [comment]
I collectionerna vi har efter parsning ser allt ok ut men för att kunna innan vi POSTar till api anropar vi System.Web.HttpUtility.UrlEncode på strängar så det skulle kunna vara problemet. Jag tror det är en gammal skuld från det att allt gick som parameters. Vi skulle kunna testa att ta bort UrlEncode. Det borde inte behövas
