### ISSUE TITLE
Handle multiple object references

### ISSUE THREAD

**Issue by winterrobert** [Senseworks-io/parser#3]
![image](https://user-images.githubusercontent.com/28933730/73211202-15f63b80-414c-11ea-983b-4bf8ba1c7e41.png)

Skulle bara fått så att när det dyker upp t.ex. en 
#TRANS 6590 {1 20 6 20}  
så skapas två transaktioner, en för {1 20} och en för {6 20}

**Comment by MrSinclair** [comment]
Denna är också klar va?
