### ISSUE TITLE
Read dimension and dimensionobject

### ISSUE THREAD

**Issue by winterrobert** [Senseworks-io/parser#5]
E.g.

#DIM		1	Kostnadsst�lle
#DIM		6	Projekt
#OBJEKT	1	0	�vrigt
#OBJEKT	1	10	"Almi. f�rinvestering"
#OBJEKT	1	20	FogGuru
#OBJEKT	6	0	"Gemensamt projekt"
#OBJEKT	6	20	"Proj FogGuru"

**Comment by MrSinclair** [comment]
Vi kan stänga denna va? Markerad som open?
