### ISSUE TITLE
Parsern: Räkna ut balanserna för varje transaktion och konto

### ISSUE THREAD

**Issue by winterrobert** [Senseworks-io/parser#7]
![image](https://user-images.githubusercontent.com/28933730/76795821-6b54dd80-67ca-11ea-9766-b6a2d33612c8.png)

- [ ] Gör en tabell i databasen som håller reda på den nuvarande balansen för varje konto efter varje transaktion (för att kunna visas i kontoanalysen)

- [ ] Gör en metod i parsern som räknar ut nuvarande balans för varje konto efter varje transaktion (för att kunna visas i kontoanalysen)

**Comment by MrSinclair** [comment]
Fixed
